-- Better Auth schema (migration to Neon — Step 2).
--
-- Generated by `@better-auth/cli generate` against api/src/lib/auth.ts, then
-- adjusted for this codebase:
--   1. `users.email_verified` gets `default false` — the table already has
--      rows (demo seed), so a NOT NULL column without a default would fail.
--   2. Better Auth's own tables use `uuid` ids (not the CLI's default `text`)
--      so `userId` FKs match our existing `users.id uuid`. With
--      `advanced.database.generateId: false`, Better Auth omits the id on
--      insert and the DB fills it via `gen_random_uuid()`.
--
-- Column names are kept exactly as Better Auth expects them (quoted camelCase)
-- so its queries resolve. These tables are Better-Auth-owned — the app never
-- touches them with raw SQL.

-- Extra columns Better Auth needs on the mapped `users` table.
alter table "users" add column "email_verified" boolean not null default false;
alter table "users" add column "image" text;

create table "session" (
  "id"         uuid not null primary key default gen_random_uuid(),
  "expiresAt"  timestamptz not null,
  "token"      text not null unique,
  "createdAt"  timestamptz not null default current_timestamp,
  "updatedAt"  timestamptz not null,
  "ipAddress"  text,
  "userAgent"  text,
  "userId"     uuid not null references "users" ("id") on delete cascade
);

create table "account" (
  "id"                     uuid not null primary key default gen_random_uuid(),
  "accountId"              text not null,
  "providerId"            text not null,
  "userId"                 uuid not null references "users" ("id") on delete cascade,
  "accessToken"            text,
  "refreshToken"           text,
  "idToken"                text,
  "accessTokenExpiresAt"   timestamptz,
  "refreshTokenExpiresAt"  timestamptz,
  "scope"                  text,
  "password"               text,
  "createdAt"              timestamptz not null default current_timestamp,
  "updatedAt"              timestamptz not null
);

create table "verification" (
  "id"          uuid not null primary key default gen_random_uuid(),
  "identifier"  text not null,
  "value"       text not null,
  "expiresAt"   timestamptz not null,
  "createdAt"   timestamptz not null default current_timestamp,
  "updatedAt"   timestamptz not null default current_timestamp
);

create index "session_userId_idx"        on "session" ("userId");
create index "account_userId_idx"        on "account" ("userId");
create index "verification_identifier_idx" on "verification" ("identifier");
